### ISSUE TITLE
"ui_flow" title in actionbar

### ISSUE THREAD

**Issue by robmr88** [sam0829/firebase_auth_ui#4]
Hi, when I launch the login/register process using 
FirebaseAuthUi.instance()
        .launchAuth
the first page that appears lets choose the login method (email, facebook etc) , the title in the action bar is "ui_flow" can that be changed?
Also, you have done a wonderful job with this. It is helping mw a lot
Thanks

**Comment by sam0829** [comment]
Hi, glad this plugin is helpful to you :) 

Regarding your issue, please set your app's name in **strings.xml** of **flutter_project/android/src/main/res/values** and then that name will appear instead of default "ui_flow".

If you don't have strings.xml file yet, please create one with following content:
```
<resources>
    <string name="app_name">Your App Name</string>
</resources>
```
**Note:** If you are testing the example app then you'll need to set app name in firebase_auth_ui/example/android/src/main/res/values folder.

**EDIT:** Please check the [Customization](https://github.com/sam0829/firebase_auth_ui#customization) section in READ ME to know more about possible customizations.

**Comment by robmr88** [comment]
Great, thank you so much. I was in fact wondering about the colors as well. 
One last question , I haven't tested it on iPhone yet, In the customization section it only gives specifics for Android, is there anything specific that must be done to customize for Iphone? (I'm a android native developer just starting to develop in Flutter so I have no idea about Iphone)
Great work !

**Comment by sam0829** [comment]
Unfortunately there's not so much to customize for iOS as in iOS the the title by default says "Welcome" and there doesn't seem to be navbar too.

That said, there's a possibility to add a logo for iOS (and Android too) which is almost ready from last 1.5-2 months but I am not getting enough time to test and publish it. If you interested in that, you can track the status [here](https://github.com/sam0829/firebase_auth_ui/issues/1).

I am closing this issue. Feel free to add comment if you still have some confusion :)

**Comment by robmr88** [comment]
It's all clear. I had a project of mine in which i used Firebase UI and now I converted it in Flutter, Your plugin helped me a lot in getting that part done. This seems to be the only working plugin in dart pub and it's working great.
 Thank you once again :D
